language: java
jdk:
- openjdk11
script:
- mvn package
before_install:
  - openssl aes-256-cbc -K $encrypted_7d2a5d2a77e8_key -iv $encrypted_7d2a5d2a77e8_iv -in secrets/718AF75F82773822E8A71DD4CF33AD49CF13F02D_private_subkeys.asc.enc -out secrets/718AF75F82773822E8A71DD4CF33AD49CF13F02D_private_subkeys.asc -d
